addons:
  postgresql: "9.6"
services:
- postgresql
before_script:
- psql -c "create user docker with superuser password 'docker';" -U postgres
- psql -c "create database technopark;" -U postgres
- psql -c "grant all on database technopark to docker;" -U postgres
language: java