services:
- postgresql
before_script:
- psql -c "create user artur with superuser password 'user';" -U postgres
- psql -c "create database technopark;" -U postgres
- psql -c "grant all on database technopark to artur;" -U postgres
language: java
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: otiNKO2p8NzFJzWe0pmm0e1FI7fBBSL2L8FYmt6lWzjMJI7P5o1X/QL99V3wV+kDAeA2SObdgrr/ILfEZcogzeEsq6Exy8p7wYn2ArTXhO1YG3LPj7XubQbm8sjinUK2HfoPl4KqKu9o2znk1fxKFZdknyVHF8cwOPsA2ndshFVeGf81ApjwX3aYCq7/9xUVx4QjNEhoD+vvcs9KAZwfB+XetI0szYLwH2ojVMTMvaF8NWzj9czSFjeGof9bRRYFL7yq7LxX/SpWZVZlQkuccr1lDL1+3MNBmED0qN2DIjtj8DGz709h/t4sTyIWt+2fdQow+YpQAY45LoR6T3gqPidEvkLGVPepe20EA6wBs/j+Hgl9Et/uGwlR6s+pkzYgMFb9+L0SV+Wr/FuCe65DkX4GEGQFw28xEapfCc4evpitcZsbejWzGQfkCpCUS8WKnIC0hH+hhfvJ/6+027ElMA3dYS8RHwAx8QF4alDTnbiUJt1q/rUzhI1CtHMzZc4BAC0s9k7ZY/611Z2ZivEDoiE/pOAcgmWAKYVFn55Ik66yocu43HOD/o9l2ejfzSpq/wZZ5gsdRK2Mz363Qi+CRZxf3aZypDPo7XZGVHR70foUBDWFoN5YkQnV2E80XejjbxFyqAGxkw+TGMgtONspDTdaO5zoIWL+MlPu3FQicxU=
  app: back42end
  on:
    repo: java-park-mail-ru/42-09-2017
    branch: develop